### PR TITLE
Update pihotspot.sh

### LINKED ISSUE #19: prepaid user setup
hello, thank you for the script, it's working.

I have a question though, how to setup/create a user with 1 hour limit?

### PR DESCRIPTION
**Pull request by reigelgallarde**
add code to update freeradius configs. So as to daloradius and freeradius can work together.
fixes #19 issue.

### CODE REVIEW

**Comment by pihomeserver** [comment]
Hi and thank you for the pull !
How do you configure the time limit accounts ? Using the session limit attribute ?

**Comment by reigelgallarde** [comment]
just add user using daloradius... everything in daloradius will now work...

Cheers!
Reigel
http://reigelgallarde.me
sent via mobile

**Comment by reigelgallarde** [comment]
you can test using quick add... it will work...

using group or plan will work too..

**Comment by pihomeserver** [comment]
Ok thank you very much for your help !!  I will add that into the new version of the script that i'm currently tested

**Comment by reigelgallarde** [comment]
yey! what have been up to this time? I might be able to help in some ways I can.

**Comment by pihomeserver** [comment]
Goal of the new script is to install all packages at the start of it, perform some checks about the user running the script, available free space, etc. Also adding use of whiptail and debconf-apt-progress to add some visual tracking
Next steps : provide an already install image and create a web interface simplified (and more modern) compared to daloradius

**Pull request merged**
